### ISSUE TITLE
This sample doesn't work

### ISSUE THREAD

**Issue by Cloudmersive** [aws-samples/aws-ecs-windows-aspnet#2]
I get this error:

CannotPullContainerError: a Windows version 10.0.16299-based image is incompatible with a 10.0.14393 host

Details here:

https://stackoverflow.com/questions/52349868/which-asp-net-windows-container-image-to-use-in-ecs-windows-docker-container-co

**Comment by Cloudmersive** [comment]
Please fix it

**Comment by ursravis** [comment]
Following mapping is the latest for windows ecs image types. Got the list from Amazon support team. Hopefully this might help you.
    AWSRegionToAMI:
        us-west-2:
            AMI: ami-b81048c0
        us-west-1:
            AMI: ami-034ba660
        us-east-2:
            AMI: ami-7cecd619
        us-east-1:
            AMI: ami-884e41f7
        eu-west-2: 
            AMI: ami-702fc517
        eu-west-1:
            AMI: ami-034ba660
        eu-central-1:
            AMI: ami-8017156b
        ca-central-1:
            AMI: ami-adbb36c9
        ap-southeast-2: 
            AMI: ami-26bd1b44
        ap-southeast-1:
            AMI: ami-dabdfb30
        ap-northeast-2:
            AMI: ami-725fe81c
        ap-northeast-1:
            AMI: ami-005621ed

**Comment by sundarnarasiman** [comment]
> I get this error:
> 
> CannotPullContainerError: a Windows version 10.0.16299-based image is incompatible with a 10.0.14393 host
> 
> Details here:
> 
> https://stackoverflow.com/questions/52349868/which-asp-net-windows-container-image-to-use-in-ecs-windows-docker-container-co

Thanks for pointing this out. We are fixing the cloud formation template to address the same.

**Comment by sundarnarasiman** [comment]
> Following mapping is the latest for windows ecs image types. Got the list from Amazon support team. Hopefully this might help you.
> AWSRegionToAMI:
> us-west-2:
> AMI: ami-b81048c0
> us-west-1:
> AMI: ami-034ba660
> us-east-2:
> AMI: ami-7cecd619
> us-east-1:
> AMI: ami-884e41f7
> eu-west-2:
> AMI: ami-702fc517
> eu-west-1:
> AMI: ami-034ba660
> eu-central-1:
> AMI: ami-8017156b
> ca-central-1:
> AMI: ami-adbb36c9
> ap-southeast-2:
> AMI: ami-26bd1b44
> ap-southeast-1:
> AMI: ami-dabdfb30
> ap-northeast-2:
> AMI: ami-725fe81c
> ap-northeast-1:
> AMI: ami-005621ed


Thanks for pointing this out. We are fixing the cloud formation template to address the same.

**Comment by sundarnarasiman** [comment]
This has been fixed.
